# Generated by Django 2.2.5 on 2021-04-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('fcid', models.IntegerField(primary_key=True, serialize=False, verbose_name='食物类别id')),
                ('fcn', models.CharField(max_length=50, verbose_name='食物类别名称')),
            ],
            options={
                'verbose_name': '食物类别表',
                'verbose_name_plural': '食物类别表',
            },
        ),
        migrations.CreateModel(
            name='NutritionCategory',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False, verbose_name='运动类别id')),
                ('nn', models.CharField(max_length=50, verbose_name='营养类别名称')),
            ],
            options={
                'verbose_name': '营养物质类别表',
                'verbose_name_plural': '营养物质类别表',
            },
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('xh', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('xm', models.CharField(max_length=10, verbose_name='姓名')),
                ('xb', models.CharField(max_length=4, verbose_name='性别')),
                ('csrq', models.DateField(verbose_name='出生日期')),
                ('jg', models.CharField(max_length=10, verbose_name='籍贯')),
                ('sjhm', models.CharField(max_length=22, verbose_name='手机号码')),
                ('mm', models.CharField(max_length=22, verbose_name='密码')),
            ],
            options={
                'verbose_name': '学生大表',
                'verbose_name_plural': '学生大表',
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False, verbose_name='运动id')),
                ('sn', models.CharField(max_length=256, verbose_name='运动名称')),
                ('sk', models.IntegerField(verbose_name='每小时卡路里')),
                ('sp', models.CharField(max_length=256, verbose_name='运动图片')),
            ],
            options={
                'verbose_name': '运动表',
                'verbose_name_plural': '运动表',
            },
        ),
        migrations.CreateModel(
            name='SportsCategory',
            fields=[
                ('scid', models.IntegerField(primary_key=True, serialize=False, verbose_name='运动类别id')),
                ('scn', models.CharField(max_length=50, verbose_name='运动类别名称')),
            ],
            options={
                'verbose_name': '运动类别表',
                'verbose_name_plural': '运动类别表',
            },
        ),
        migrations.CreateModel(
            name='studd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=256, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('sex', models.CharField(max_length=256, verbose_name='性别')),
                ('height', models.IntegerField(verbose_name='身高')),
                ('weight', models.IntegerField(verbose_name='体重')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='SportsRecord',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False, verbose_name='运动记录id')),
                ('st', models.IntegerField(verbose_name='运动时长')),
                ('sd', models.DateTimeField(auto_now_add=True, verbose_name='运动日期')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiGuang.Sports', verbose_name='运动id')),
            ],
            options={
                'verbose_name': '运动记录表',
                'verbose_name_plural': '运动记录表',
            },
        ),
        migrations.AddField(
            model_name='sports',
            name='scid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiGuang.SportsCategory', verbose_name='运动类别id'),
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False, verbose_name='食物id')),
                ('nc', models.IntegerField(verbose_name='含量')),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiGuang.NutritionCategory', verbose_name='营养物质id')),
            ],
            options={
                'verbose_name': '营养物质表',
                'verbose_name_plural': '营养物质表',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False, verbose_name='食物id')),
                ('fn', models.CharField(max_length=256, verbose_name='食物名称')),
                ('fk', models.IntegerField(verbose_name='每克卡路里')),
                ('ap', models.CharField(max_length=256, verbose_name='适宜人群')),
                ('nap', models.CharField(max_length=256, verbose_name='不适人群')),
                ('fp', models.CharField(max_length=256, verbose_name='食物图片')),
                ('fcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiGuang.FoodCategory', verbose_name='食物类别id')),
            ],
            options={
                'verbose_name': '食物表',
                'verbose_name_plural': '食物表',
            },
        ),
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('drid', models.IntegerField(primary_key=True, serialize=False, verbose_name='饮食记录id')),
                ('fw', models.IntegerField(verbose_name='食物重量')),
                ('dd', models.DateTimeField(auto_now_add=True, verbose_name='饮食日期')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiGuang.Food', verbose_name='食物id')),
            ],
            options={
                'verbose_name': '饮食记录表',
                'verbose_name_plural': '饮食记录表',
            },
        ),
    ]
