# Generated by Django 2.2.5 on 2021-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiGuang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritioncategory',
            name='nid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='营养物质id'),
        ),
        migrations.AlterField(
            model_name='nutritioncategory',
            name='nn',
            field=models.CharField(max_length=50, verbose_name='营养物质名称'),
        ),
    ]
