# Generated by Django 2.2.5 on 2021-04-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShiGuang', '0002_auto_20210429_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrecord',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ShiGuang.User', verbose_name='用户id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsrecord',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ShiGuang.User', verbose_name='用户id'),
            preserve_default=False,
        ),
    ]
