# Generated by Django 2.2.5 on 2021-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiGuang', '0003_auto_20210429_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecord',
            name='dd',
            field=models.DateField(verbose_name='饮食日期'),
        ),
        migrations.AlterField(
            model_name='sportsrecord',
            name='sd',
            field=models.DateField(verbose_name='运动日期'),
        ),
    ]
